name: PermissionWhitelist
version: '${version}'
main: work.microhand.permissionwhitelist.PermissionWhitelist
api-version: '1.20'
commands:
  pw:
    description: the main command of the permission whitelist
    usage: /pw